name: Build Windows package

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'docs_src/**'
      - 'README.md'
      - 'CITATION'
      - 'CONTRIBUTING.md'
    #tags: [ 'v*.*.*', 'dev*.*.*' ]

jobs:
  build_rpm:
    name: Build RPM package
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Windows SDK
        run: Invoke-WebRequest -Uri https://scaphandre.s3.fr-par.scw.cloud/utils/winsdksetup_win11.exe -OutFile winsdksetup.exe 
      - name: Install SDK
        run: winsdksetup.exe /s /v" /qn License=Yes
      - name: Download Windows WDK
        run: Invoke-WebRequest -Uri https://scaphandre.s3.fr-par.scw.cloud/utils/wdksetup_win11.exe -OutFile wdksetup.exe 
      - name: Install WDK
        run: wdksetup.exe /s /v" /qn License=Yes
        

