name: Build Windows package

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'docs_src/**'
      - 'README.md'
      - 'CITATION'
      - 'CONTRIBUTING.md'
    #tags: [ 'v*.*.*', 'dev*.*.*' ]

jobs:
  build_rpm:
    name: Build RPM package
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Windows SDK
        run: Invoke-WebRequest -Uri https://scaphandre.s3.fr-par.scw.cloud/utils/winsdksetup_win11.exe -OutFile winsdksetup.exe 
      - name: Install SDK
        run: .\winsdksetup.exe /v /qn License=Yes
      - name: Download Windows WDK
        run: Invoke-WebRequest -Uri https://scaphandre.s3.fr-par.scw.cloud/utils/wdksetup_win11.exe -OutFile wdksetup.exe 
      - name: Install WDK
        run: .\wdksetup.exe /v /qn License=Yes
      - name: Check what is in C:\Program Files (x86)\Windows Kits
        run: ls "C:\Program Files (x86)\Windows Kits\"
      #- name: Setup WDK
      #  run: C:\"Program Files (x86)"\Windows Kits\10\Vsix\VS2022\10.0.22621.382\WDK.vsix
      - name: Check what is in C:\Program Files (x86)\Windows Kits\10\bin
        run: ls "C:\Program Files (x86)\Windows Kits\10\bin"
      - name: Generate self-signed certificate
        run: C:\Program Files (x86)\Windows Kits\10\bin\MakeCert.exe -r -pe -ss PrivateCertStore -n CN=hubblo.org -eku 1.3.6.1.5.5.7.3.3 ScaphandreDrvTest.cer
      - run: C:\Program Files (x86)\Windows Kits\10\bin\stampinf.exe -f .\ScaphandreDrv\ScaphandreDrv.inf -d 03/11/2023 -v 0.0.1
      - run: C:\Program Files (x86)\Windows Kits\10\bin\Inf2Cat.exe /driver:.\ScaphandreDrv\ /os:10_X64  
      - run: .\signtool.exe sign /v /fd sha256 /s PrivateCertStore /n hubblo.org ".\ScaphandreDrv\scaphandredrv.cat"
      - run: .\certmgr.exe /add ".\ScaphandreDrv\ScaphandreDrvTest.cer" /s /r localMachine root
      - run: & "C:\Program Files (x86)\Windows Kits\10\Tools\10.0.22621.0\x64\devcon.exe" install .\ScaphandreDrv.inf root\SCAPHANDREDRV
